export const sfsBaseTextures: {colorTex: Record<string, boolean>, shapeTex: Record<string, boolean>} = {
  colorTex: {
    "A USA": true,
    "Array": true,
    "Arrows": true,
    "Color_Black": true,
    "Color_Gray": true,
    "Color_Orange": true,
    "Color_White": true,
    "Gold_Foil": true,
    "Metal": true,
    "Metal_2": true,
    "Metal_3": true,
    "Metal_4": true,
    "Nozzle_2": true,
    "Nozzle_3": true,
    "Pattern_Bars": true,
    "Pattern_Bars_Band": true,
    "Pattern_Bars_Half": true,
    "Pattern_Cone": true,
    "Pattern_Half": true,
    "Pattern_Squares": true,
    "R Stripes 1": true,
    "R Stripes 2": true,
    "R Stripes": true,
    "R USA - Skin": true,
    "R USA 0": true,
    "R USA 1": true,
    "SV_S1_Flag": true,
    "SV_S1_USA": true,
    "SV_S2": true,
    "SV_S3": true,
    "Strut_Gray": true,
    "Strut_Gray_2": true
  },
  shapeTex: {
    "Edges Faces Bottom": true,
    "Edges Faces Top": true,
    "Edges Faces": true,
    "Edges Smooth": true,
    "Edges Thin Top": true,
    "Edges Thin": true,
    "Edges thin Bottom": true,
    "Fairing Edges": true,
    "Fairing": true,
    "Flat Faces": true,
    "Flat Smooth 4": true,
    "Flat Smooth": true,
    "Flat": true,
    "Half Rivets": true,
    "Interstage Full": true,
    "Interstage": true,
    "Metal Bands": true,
    "Nozzle_4": true,
    "RA Capsule 1": true,
    "RA Capsule 2": true,
    "Rivets": true,
    "Strut 2": true,
    "Strut 3": true,
    "Strut": true
  }
}